inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - drafts/**/*
    - log/*
    - vendor/**/*
    - tmp/**/*
    - public/**/*
    - deploy/*
    - doc/*
    - coverage/**/*
    - node_modules/**/*


Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
